# Generated by Django 4.2.5 on 2023-10-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_temtransaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="payer",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="recipient",
        ),
        migrations.AlterField(
            model_name="temtransaction",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
