# Generated by Django 4.2.5 on 2023-10-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0004_transaction_payer_transaction_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
